/* include/api_cfgDebug.h.  Generated by configure.  */
/* include/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if you have PTRACE_GETFPXREGS */
#define HAVE_PTRACE_GETFPXREGS 1

/* Define if you are running *BSD */
/* #undef OS_BSD */

/* Define if you are running FreeBSD */
/* #undef OS_FREEBSD */

/* Define if you are running Linux */
#define OS_LINUX 1

/* Define if you are running NetBSD */
/* #undef OS_NETBSD */

/* Define if you are running OpenBSD */
/* #undef OS_OPENBSD */
