/* include/cfgDebug.h.  Generated by configure.  */
/* include/cfgDebug.h.in.  Generated from configure.ac by autoheader.  */

/* Define if you have PTRACE_GETFPXREGS */
#define HAVE_PTRACE_GETFPXREGS 1

/* Define if you are running *BSD */
/* #undef OS_BSD */

/* Define if you are running FreeBSD */
/* #undef OS_FREEBSD */

/* Define if you are running Linux */
#define OS_LINUX 1

/* Define if you are running NetBSD */
/* #undef OS_NETBSD */

/* Define if you are running OpenBSD */
/* #undef OS_OPENBSD */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "libDebug"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libDebug 0.1.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libdebug"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1
