/* include/api_cfgDASM.h.  Generated by configure.  */
/* include/cfgDASM.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define if you are running an Intel x86 cpu */
#define INTEL86 1
