/* include/cfgDASM.h.  Generated by configure.  */
/* include/cfgDASM.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define if you are running an Intel x86 cpu */
#define INTEL86 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "libDASM"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libDASM 0.1.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libdasm"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1.2"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1
