/* include/defs.h.  Generated by configure.  */
/* include/defs.h.in.  Generated from configure.ac by autoheader.  */

/* Define to number of bytes in two machine words */
#define DWORD 4

/* Define to number of bytes in half a machine word */
#define HALFWORD 1

/* Define if you have the readline library */
#define HAVE_READLINE 1

/* Define if you have readline/history.h */
#define HAVE_READLINE_HISTORY_H 1

/* Define if you have readline/readline.h */
#define HAVE_READLINE_READLINE_H 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define if you have termios.h */
#define HAVE_TERMIOS_H 1

/* Define if you have termio.h */
#define HAVE_TERMIO_H 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Name of package */
#define PACKAGE "ald"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "ald"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "ald 0.1.7"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "ald"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1.7"

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Version number of package */
#define VERSION "0.1.7"

/* Define to number of bytes in one machine word */
#define WORDSIZE 2
